
services:
  redis:
    image: redis:7-alpine
    container_name: redis_lunch
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    hostname: redis_lunch
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - /var/www/lunch:/var/www/lunch:ro
      - ./ssl:/etc/ssl
    depends_on:
      - fastapi
    networks:
      - app_network

  fastapi:
    build: .
    container_name: fastapi
    environment:
      - TZ=Europe/Moscow
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "4443:443"
    volumes:
      - ./ssl:/etc/ssl
    command: >
      uvicorn main:app --host 0.0.0.0 --port 443
      --proxy-headers
      --forwarded-allow-ips '*'
    networks:
      - app_network


  celery:
    build: .
    container_name: celery
    environment:
      - TZ=Europe/Moscow
      - CELERY_BROKER_URL=redis://redis_lunch:6379/1
      - CELERY_RESULT_BACKEND=redis://redis_lunch:6379/1
      - FLOWER_BASIC_AUTH=user:password
    restart: unless-stopped
    depends_on:
      - redis
      - fastapi
    ports:
      - "5556:5555"  # Flower dashboard
    networks:
      - app_network
    command: >
      sh -c "celery -A tasks worker --concurrency=1 --loglevel=info
      & celery -A tasks beat
      & celery -A tasks flower --port=5555 --basic_auth=$$FLOWER_BASIC_AUTH"

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
