"""edit model order and order item

Revision ID: 300a55ae4fb1
Revises: 3d35ea7f687d
Create Date: 2025-04-04 19:01:23.469761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300a55ae4fb1'
down_revision: Union[str, None] = '3d35ea7f687d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dish_variants_dish_id_fkey', 'dish_variants', type_='foreignkey')
    op.create_foreign_key(None, 'dish_variants', 'dish', ['dish_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('order_items', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_dish_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'dish', ['dish_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_column('order_items', 'quantity')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('order_items', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_items', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order_items', schema='public', type_='foreignkey')
    op.create_foreign_key('order_items_dish_id_fkey', 'order_items', 'dish', ['dish_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_column('order_items', 'variant_id')
    op.drop_column('order_items', 'count')
    op.drop_constraint(None, 'dish_variants', schema='public', type_='foreignkey')
    op.create_foreign_key('dish_variants_dish_id_fkey', 'dish_variants', 'dish', ['dish_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
