"""add_order_amount_and_status_enum

Revision ID: 3d35ea7f687d
Revises: 36d17617b438
Create Date: 2025-04-03 23:34:53.142458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d35ea7f687d'
down_revision: Union[str, None] = '36d17617b438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    order_status_enum = postgresql.ENUM(
        'Оформлено', 'Выполнено', 'Отменено', 'Удалено', 'Неизвестно',
        name='order_status_enum',
        create_constraint=True
    )
    order_status_enum.create(op.get_bind())
    op.add_column('orders', sa.Column(
        'order_status',
        order_status_enum,
        server_default='Оформлено',
        nullable=False
    ))
    op.drop_constraint('dish_variants_dish_id_fkey', 'dish_variants', type_='foreignkey')
    op.create_foreign_key(None, 'dish_variants', 'dish', ['dish_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('order_items_dish_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'dish', ['dish_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('orders', sa.Column('amount', sa.Float(), nullable=False))
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_status')    
    op.execute("DROP TYPE order_status_enum")    
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('orders', 'amount')
    op.drop_constraint(None, 'order_items', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order_items', schema='public', type_='foreignkey')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('order_items_dish_id_fkey', 'order_items', 'dish', ['dish_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'dish_variants', schema='public', type_='foreignkey')
    op.create_foreign_key('dish_variants_dish_id_fkey', 'dish_variants', 'dish', ['dish_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
