"""add id in iiko

Revision ID: 9803ffb230a9
Revises: 6e34c4e78742
Create Date: 2025-05-05 15:21:41.693325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9803ffb230a9'
down_revision: Union[str, None] = '6e34c4e78742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('id_iiko', sa.Integer(), nullable=True))
    op.drop_constraint('dish_variants_dish_id_fkey', 'dish_variants', type_='foreignkey')
    op.create_foreign_key(None, 'dish_variants', 'dish', ['dish_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('order_items_variant_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_dish_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'dish_variants', ['variant_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'order_items', 'dish', ['dish_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'order_items', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order_items', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order_items', schema='public', type_='foreignkey')
    op.create_foreign_key('order_items_dish_id_fkey', 'order_items', 'dish', ['dish_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('order_items_variant_id_fkey', 'order_items', 'dish_variants', ['variant_id'], ['id'])
    op.drop_constraint(None, 'dish_variants', schema='public', type_='foreignkey')
    op.create_foreign_key('dish_variants_dish_id_fkey', 'dish_variants', 'dish', ['dish_id'], ['id'], ondelete='CASCADE')
    op.drop_column('dish', 'id_iiko')
    # ### end Alembic commands ###
